### ISSUE TITLE
Python support for pipenv or/and poetry

### ISSUE THREAD

**Issue by gameboy86** [charludo/projectmgr.nvim#14]
Hi,  @charludo. At the beginning I will say it's great plugin.
I have a question about running pipenv or poetry python virtual env when switching projects. I tried to add "pipenv shell" in startup script, but it doesn't seem to work. Do you have some idea how to run virtualenv using your plugin ?

**Comment by charludo** [comment]
Hi!

Yeah, it appears it's a lot more complicated to activate a venv than I would have thought. You might want to check out [vim-venom](https://github.com/rafi/vim-venom) for that prpose and invoke it from projectmgr. Fair warning though: I haven't exactly gotten vim-venom to run error free.

If you find a good way to do this, let me know, otherwise I'll look into it at some point.
